//! The operator's console: one page, assembled here, served by the API at `/`.
//!
//! ## What it is for
//!
//! The platform has no transient states. There is what was asked for (`spec`),
//! what is (`status`), and `generation` against `observed_generation` to say
//! whether the second has caught up with the first. That is a good model and a
//! terrible thing to read raw, so this is the interface that makes it legible:
//! every object leads with a verdict — settled, drifting, failing, not
//! reported, deleting — and every verdict is derived from those two numbers and
//! the `Ready` condition, in one function, so no two screens can disagree about
//! whether something is stuck.
//!
//! An operator should never have to ask "is it converged, and if not, why".
//! That question is answered on the object, above the fold, with the reason and
//! the sentence the agent wrote.
//!
//! ## One file, nothing fetched
//!
//! No CDN, no webfont, no icon set, no framework. A cloud console is opened
//! during an incident, sometimes from a network that can reach the API and
//! nothing else, and a page that half-renders because it cannot reach the
//! internet is worse than no page. Everything is inlined here at build time and
//! a test below checks that nothing crept back in.
//!
//! ## The schema is the console
//!
//! There is no per-type screen. [`schema::COLLECTIONS`] describes each
//! collection — its fields and how each one is asked for, its list columns, and
//! the spec/status pairs worth showing side by side — and the script renders
//! all of it generically. A collection added to the platform is an entry there,
//! not a new page, which is the console's half of the model's promise that
//! everything is the same shape.

mod schema;

use std::sync::OnceLock;

pub use schema::{
    Agreement, COLLECTIONS, Cell, Check, Choice, Collection, Column, Field, Kind, Scale, Scope,
};

const SHELL: &str = include_str!("assets/shell.html");
const TOKENS_CSS: &str = include_str!("assets/tokens.css");
const LIGHT_CSS: &str = include_str!("assets/light.css");
const CONSOLE_CSS: &str = include_str!("assets/console.css");

/// The script, in the order it is concatenated. All of it shares one scope, so
/// the order is the dependency order at *load* time only — everything that
/// calls across a boundary does so from a function body, after the whole page
/// exists.
const SCRIPT: &[(&str, &str)] = &[
    ("dom", include_str!("assets/dom.js")),
    ("model", include_str!("assets/model.js")),
    ("api", include_str!("assets/api.js")),
    ("board", include_str!("assets/board.js")),
    ("detail", include_str!("assets/detail.js")),
    ("form", include_str!("assets/form.js")),
    ("migrate", include_str!("assets/migrate.js")),
    ("app", include_str!("assets/app.js")),
];

const CSS_MARKER: &str = "/*=CSS=*/";
const JS_MARKER: &str = "/*=JS=*/";

/// The whole console, as one document.
pub fn page() -> String {
    page_ref().to_string()
}

/// The same page without copying it per request, for a server that holds it for
/// the lifetime of the process.
pub fn page_ref() -> &'static str {
    static PAGE: OnceLock<String> = OnceLock::new();
    PAGE.get_or_init(build)
}

fn build() -> String {
    SHELL
        .replace(CSS_MARKER, &stylesheet())
        .replace(JS_MARKER, &script())
}

fn stylesheet() -> String {
    let mut css =
        String::with_capacity(TOKENS_CSS.len() + CONSOLE_CSS.len() + LIGHT_CSS.len() * 2 + 256);
    css.push_str(TOKENS_CSS);
    // The light ramp, written once and applied twice — once for the system
    // preference, once for an explicit choice. A media query cannot join a
    // selector list, and a second hand-kept copy is exactly how the two
    // appearances drift apart, so the copy is made here instead. The `:not()`
    // is what lets an explicit dark choice beat a light system preference.
    css.push_str("\n@media (prefers-color-scheme: light) {\n  :root:not([data-theme=\"dark\"]) {");
    css.push_str(LIGHT_CSS);
    css.push_str("}\n}\n:root[data-theme=\"light\"] {");
    css.push_str(LIGHT_CSS);
    css.push_str("}\n");
    css.push_str(CONSOLE_CSS);
    css
}

fn script() -> String {
    let mut js = String::with_capacity(64 * 1024);
    js.push_str("\"use strict\";\n");
    js.push_str("// Generated by velstra-cloud-console. Every section below is a file in\n");
    js.push_str("// velstra-cloud-console/src/assets/, concatenated in one scope.\n");
    js.push_str("const SCHEMA = ");
    // `<` cannot appear raw inside a `<script>` block without risking an early
    // close of the element. Nothing in the schema contains one today; escaping
    // it means nothing ever has to.
    js.push_str(&schema::as_json().replace('<', "\\u003c"));
    js.push_str(";\n");
    for (name, source) in SCRIPT {
        js.push_str("\n// ==== ");
        js.push_str(name);
        js.push_str(".js ====\n");
        js.push_str(source);
    }
    js
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_document_is_whole() {
        let page = page();
        assert!(
            !page.contains(CSS_MARKER),
            "the stylesheet was never spliced in"
        );
        assert!(!page.contains(JS_MARKER), "the script was never spliced in");
        assert!(page.starts_with("<!doctype html>"));
        assert!(page.contains("</html>"));
        // Every section of the script has to be in there: a file dropped from
        // the list still compiles and still serves a page, and the page is dead
        // from whichever function was in it onwards.
        for (name, _) in SCRIPT {
            assert!(
                page.contains(&format!("==== {name}.js ====")),
                "{name}.js is missing"
            );
        }
    }

    #[test]
    fn nothing_is_fetched_from_outside_the_page() {
        // An operator opens this during an incident, sometimes from a network
        // that can reach the API and nothing else. One `<link>` to a font is
        // enough to make the page arrive unstyled at the worst moment, and it
        // is the kind of thing that gets added back in a hurry.
        let page = page();
        for forbidden in [
            "<link",
            "<img",
            "<script src",
            "@import",
            "url(http",
            "//fonts.",
            "cdn.",
        ] {
            assert!(
                !page.contains(forbidden),
                "the page reaches outside itself: {forbidden}"
            );
        }
        // `fetch` is used, but only ever against a path on this same origin.
        for (name, source) in SCRIPT {
            for line in source.lines().filter(|l| l.contains("fetch(")) {
                assert!(
                    !line.contains("http://") && !line.contains("https://"),
                    "{name}.js fetches an absolute URL: {line}"
                );
            }
        }
    }

    #[test]
    fn both_appearances_come_from_one_ramp() {
        let css = stylesheet();
        // Twice, and from the same source. Once means an appearance is missing;
        // a hand-written second copy is how they drift.
        assert_eq!(
            css.matches("--bg-app: #f4f6fa").count(),
            2,
            "the light ramp is not applied twice"
        );
        assert!(css.contains(":root:not([data-theme=\"dark\"])"));
        assert!(css.contains(":root[data-theme=\"light\"]"));
    }

    #[test]
    fn the_schema_reaches_the_script() {
        let page = page();
        assert!(page.contains("const SCHEMA = ["));
        assert!(page.contains(r#""id":"instances""#));
        assert!(page.contains(r#""id":"operations""#));
    }

    #[test]
    fn the_page_never_writes_wire_data_into_the_parser() {
        // Everything on this page came off the wire — a condition message
        // written by an agent, a label an operator typed. `innerHTML` over any
        // of it is markup injection with extra steps, so the helper that builds
        // elements refuses it and no section may reach around that.
        for (name, source) in SCRIPT {
            for (n, line) in source.lines().enumerate() {
                let code = line.trim_start();
                if code.starts_with("//") || code.starts_with("*") {
                    continue;
                }
                assert!(
                    !code.contains("innerHTML") && !code.contains("insertAdjacentHTML"),
                    "{name}.js:{} writes markup from data",
                    n + 1
                );
            }
        }
    }

    #[test]
    fn no_component_names_a_colour_of_its_own() {
        // Colour is a code here: green settled, red failing, amber drifting,
        // blue "you are here" and the one primary action, plus neutral for what
        // a thing merely *is*. A component that reaches for a raw value has
        // left the code, and the two appearances stop agreeing the moment it
        // does — the light ramp can only re-point tokens.
        let literals = [
            ("a hex", hex_colours(CONSOLE_CSS)),
            (
                "an rgb()",
                CONSOLE_CSS.matches("rgb(").count() + CONSOLE_CSS.matches("rgba(").count(),
            ),
            ("an hsl()", CONSOLE_CSS.matches("hsl(").count()),
        ];
        for (kind, literal) in literals {
            assert_eq!(
                literal, 0,
                "console.css names {kind} colour instead of using a token"
            );
        }
    }

    /// `#f85149` is a colour; `#sheet` is a selector. A run of hex digits of a
    /// colour's length, not followed by more word characters.
    fn hex_colours(css: &str) -> usize {
        let bytes = css.as_bytes();
        let mut found = 0;
        for (i, b) in bytes.iter().enumerate() {
            if *b != b'#' {
                continue;
            }
            let run = bytes[i + 1..]
                .iter()
                .take_while(|c| c.is_ascii_hexdigit())
                .count();
            let ends = bytes
                .get(i + 1 + run)
                .is_none_or(|c| !c.is_ascii_alphanumeric() && *c != b'-' && *c != b'_');
            if ends && matches!(run, 3 | 4 | 6 | 8) {
                found += 1;
            }
        }
        found
    }
}
