// Hold the fixture to the shape the real API was recorded answering.
//
// `fake-api.mjs` is the contract in memory, which is what lets the console be
// written and tested without this repository's server running. The cost of that
// is two implementations of every custom method with nothing between them: a
// verb that answers `largestStartable` in one and `largest_startable` in the
// other passes both suites and fails the first time a browser meets the real
// server.
//
// So the API records what it answers — `velstra-cloud-api/tests/contract_shapes.rs`,
// which writes `velstra-cloud-api/tests/contract/shapes.json` — and this holds
// the fixture to it. One artifact, generated by the implementation that ships.
//
// Values are not compared: the two fixtures describe different cells on
// purpose. `null` and `[]` on either side mean "this fixture had nothing here",
// which is a fact about the fixture rather than about the contract. What is
// left is what actually breaks a screen: a key spelled differently, missing, or
// holding a number on one side and a string on the other.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const RECORDING = resolve(here, "../../../velstra-cloud-api/tests/contract/shapes.json");

/// What a value looks like, with the values taken out. The same rules as the
/// Rust side, and they have to stay the same rules.
function shape(value) {
  if (value === null || value === undefined) return "null";
  if (Array.isArray(value)) return value.length ? [shape(value[0])] : [];
  switch (typeof value) {
    case "boolean": return "bool";
    case "number": return "number";
    case "string": return "string";
    case "object": {
      const out = {};
      for (const key of Object.keys(value).sort()) out[key] = shape(value[key]);
      return out;
    }
    default: return "null";
  }
}

// `{}` counts too: an object with nothing in it — a resource with no labels —
// says as little about the contract as a null or an empty list.
const empty = (s) =>
  s === "null" ||
  (Array.isArray(s) && s.length === 0) ||
  (s && typeof s === "object" && !Array.isArray(s) && Object.keys(s).length === 0);

function agrees(recorded, fresh, path, gaps) {
  if (empty(recorded) || empty(fresh)) return;
  const bothObjects = (a, b) =>
    a && b && typeof a === "object" && !Array.isArray(a) && typeof b === "object" && !Array.isArray(b);
  if (bothObjects(recorded, fresh)) {
    for (const key of Object.keys(recorded)) {
      if (!(key in fresh)) gaps.push(`${path}.${key} is what the API answers and the fixture does not`);
      else agrees(recorded[key], fresh[key], `${path}.${key}`, gaps);
    }
    for (const key of Object.keys(fresh)) {
      if (!(key in recorded)) gaps.push(`${path}.${key} is in the fixture and not in the API's answer`);
    }
    return;
  }
  if (Array.isArray(recorded) && Array.isArray(fresh)) {
    agrees(recorded[0], fresh[0], `${path}[]`, gaps);
    return;
  }
  if (JSON.stringify(recorded) !== JSON.stringify(fresh)) {
    gaps.push(`${path} is ${JSON.stringify(recorded)} from the API and ${JSON.stringify(fresh)} here`);
  }
}

/// Names the console reads out of an object that no recorded answer contains.
///
/// The other half of the same hazard, and the one that bit: the console read
/// `spec.reason` off an audit record, which has `detail`, so every refusal in
/// the history panel rendered blank — silently, because a missing key in
/// JavaScript is `undefined` and `undefined || ""` is a perfectly good empty
/// string.
///
/// Only the `pick(spec(x), "name")` form is checked, which is how this console
/// reads a field it did not get from the schema. A name that is genuinely
/// right and simply not in the recording belongs in `ELSEWHERE` with a line
/// saying where it does come from — but the better fix is usually to add that
/// request to `contract_shapes.rs`, because then it is checked rather than
/// excused.
const ELSEWHERE = {
  // `MigrationSpec.instance`. Migrations are not in the recording because the
  // fixtures' guests are not mid-transfer; `:explainMigration` is.
  instance: "migration.spec.instance",
};

export function checkReads(recorded) {
  const file = process.env.CONSOLE_JS;
  if (!file) return { skipped: "CONSOLE_JS is not set, so nothing was read" };
  let source;
  try {
    source = readFileSync(file, "utf8");
  } catch (e) {
    return { skipped: `cannot read ${file} (${e.code || e.message})` };
  }

  // Three pools, not one. A single set of "every key anywhere in any answer"
  // is too coarse to catch the bug this exists for: `reason` appears in the
  // CPU advice, so reading `spec.reason` off an audit record — which has
  // `detail` — would have passed. What is asked here is the real question:
  // does *this half of an object* have a field by that name.
  const pools = { spec: new Set(), status: new Set(), meta: new Set() };
  const collect = (v, into) => {
    if (Array.isArray(v)) return v.forEach((x) => collect(x, into));
    if (!v || typeof v !== "object") return;
    for (const [k, x] of Object.entries(v)) {
      if (into) { into.add(k); collect(x, into); continue; }
      collect(x, pools[k]);
    }
  };
  collect(recorded, null);

  const reads = [];
  const pattern = /pick\((spec|status|meta)\([^)]*\),\s*"([A-Za-z][A-Za-z0-9]*)"/g;
  for (const m of source.matchAll(pattern)) reads.push([m[1], m[2]]);

  const gaps = [];
  const seen = new Set();
  for (const [half, name] of reads) {
    const key = half + "." + name;
    if (seen.has(key)) continue;
    seen.add(key);
    if (pools[half].has(name) || name in ELSEWHERE) continue;
    gaps.push(`the console reads ${key} and no recorded ${half} has a field by that name`);
  }
  return { gaps, checked: seen.size };
}

export async function checkShapes(base, token) {
  let recorded;
  try {
    recorded = JSON.parse(readFileSync(RECORDING, "utf8"));
  } catch (e) {
    // Not a failure: this file can be run against a checkout without the Rust
    // side built, or from a packaged console. Saying so is better than either
    // pretending to have checked or refusing to run the suite.
    return { skipped: `no recording at ${RECORDING} (${e.code || e.message})` };
  }

  const gaps = [];
  const reads = checkReads(recorded);
  if (reads.gaps) gaps.push(...reads.gaps);
  for (const [request, want] of Object.entries(recorded)) {
    const url = new URL("api/v1/" + request, base);
    const answer = await fetch(url, { headers: { Authorization: "Bearer " + token } });
    if (!answer.ok) {
      gaps.push(`${request} answered ${answer.status} here and is recorded as an answer`);
      continue;
    }
    agrees(want, shape(await answer.json()), request, gaps);
  }
  return { gaps, checked: Object.keys(recorded).length };
}
